feat: 📦: Issue #79 Banner component added in features
AkijVenture/akij-turborepo pull request #87
Opened 2023-01-09 08:35 UTC by urmirahman

# Description

Followed by the ticket #78 In this PR Banner component is created for Single Product.

Fixes # (issue)

## New Button Variants are created
## New Feature  as `Banner` is created
## Banner component has divided in other small components.
## Same changes added in storybook Features and buttons. 

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## UI in server localhost:3010
![banner](https://user-images.githubusercontent.com/44704518/211267085-4c24e8f0-7234-42e4-9a0c-0bc054c3d4af.png)

## storybook

https://user-images.githubusercontent.com/44704518/211267423-40237b55-1926-4dae-b205-d11699b56e0a.mp4

2023-01-09 09:34 UTC, TanvirAlam requested changes
LGTM :+1: 

so far, real nice PR. please make sure you cook all your food like this. Please Thank you

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/pages/index.tsx
> +          {/* banner will be deleted after completion of task */}
do not put extra comments, no need, delete it. we know this is practice

2023-01-09 09:34 UTC, TanvirAlam commented on packages/ui/components/elements/Buttons/Button.stories.tsx
> +
Whats this, this is not part of the issue? this file should not be here

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/Banner.tsx
> +        {products[0] && <ProductImage src={urlForThumbnail(products[0].image as string)} />}
you are already using `error` and `loading`, why not pass it here and use it?

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/ProductImage.tsx
> +      <img className="h-96" src={src} alt="Product image" />
`h-96`? wont this create extra space for other components?

Also try using `<Image />` next js one see if you can

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +      <h1 className="mt-5">{title}</h1>
you are having `mt-5` in 3 places? is that needes in 3 places?

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +      <p className="mt-5 text-lg ">{description}</p>
`text-lg`? on a description?

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/ProductImage.tsx
> +      <img className="h-96" src={src} alt="Product image" />
Also look at `alt` that static text, try passing the title and added it here

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply flex flex-col justify-center  px-6 md:justify-start;
you have extra space, butter why?

2023-01-09 09:34 UTC, TanvirAlam commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply rounded-full border border-green-500 py-4 px-6 text-center text-green-700  transition duration-300 hover:shadow-md hover:shadow-green-300;
you have extra space, butter why?

2023-01-09 09:41 UTC, urmirahman commented on apps/akij-food-beverage/src/pages/index.tsx
> +          {/* banner will be deleted after completion of task */}
Okay I'll delete it.

2023-01-09 09:45 UTC, urmirahman commented on packages/ui/components/elements/Buttons/Button.stories.tsx
> +
Accidently added one extra empty line while checking the page. your coding style.

2023-01-09 09:48 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/Banner.tsx
> +        {products[0] && <ProductImage src={urlForThumbnail(products[0].image as string)} />}
Didn't noticed it. I'll follow this way then.

2023-01-09 09:55 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/Banner.tsx
> +        {products[0] && <ProductImage src={urlForThumbnail(products[0].image as string)} />}
Used Loading for data check now

2023-01-09 09:59 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/ProductImage.tsx
> +      <img className="h-96" src={src} alt="Product image" />
Yeah now Image from nextjs is used here and extra h-96 is removed

2023-01-09 10:04 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +      <h1 className="mt-5">{title}</h1>
Looks good with some spaces. How about I do this with gap-5 in the Box classname??

2023-01-09 10:04 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +      <p className="mt-5 text-lg ">{description}</p>
Thought is would look good. now removed because it doesn't

2023-01-09 10:06 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/ProductImage.tsx
> +      <img className="h-96" src={src} alt="Product image" />
Okay I'll add title here

2023-01-09 10:10 UTC, urmirahman commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply flex flex-col justify-center  px-6 md:justify-start;
Butter removed

2023-01-09 10:10 UTC, urmirahman commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply rounded-full border border-green-500 py-4 px-6 text-center text-green-700  transition duration-300 hover:shadow-md hover:shadow-green-300;
Butter removed

2023-01-09 10:22 UTC, urmirahman commented
@TanvirAlam changes are made. If its okay now.

2023-01-09 12:17 UTC, TanvirAlam requested changes
Small little changes, after this we can approve this

2023-01-09 12:17 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Button.tsx
> +  return <button className={classname}>{text}</button>
the `classname` is famous keyboard, try renaming this to something else

2023-01-09 12:17 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Buttons.stories.tsx
> +export const BuyNow: ComponentStory<typeof Button> = () => <Button classname="primaryBtn" text={'Buy Now'} />
why are you exporting them?

2023-01-09 12:17 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Buttons.stories.tsx
> +export const SeeMore: ComponentStory<typeof Button> = () => <Button classname="outlineBtn" text={'See More'} />
why are you exporting them?

2023-01-09 12:17 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +        <Button text={actionBtnOne} classname="primaryBtn" />
ooo isn't this `className`? 
![image](https://user-images.githubusercontent.com/3250040/211305897-88d9cd71-c7b9-47aa-a58a-c2b88b398630.png)

2023-01-09 12:17 UTC, TanvirAlam commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply rounded-full border border-green-500 py-4 px-6 text-center text-green-700  transition duration-300 hover:shadow-md hover:shadow-green-300;
you have extra space after `text-green-700`

2023-01-09 12:17 UTC, TanvirAlam commented on packages/ui/components/elements/Buttons/Button.tsx
> +};
Please add a new line

2023-01-10 02:36 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Button.tsx
> +  return <button className={classname}>{text}</button>
changed the classname to styleClass

2023-01-10 02:37 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Buttons.stories.tsx
> +export const BuyNow: ComponentStory<typeof Button> = () => <Button classname="primaryBtn" text={'Buy Now'} />
Fixed it . Now its not exported

2023-01-10 02:37 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/elements/buttons/Buttons.stories.tsx
> +export const SeeMore: ComponentStory<typeof Button> = () => <Button classname="outlineBtn" text={'See More'} />
Fixed it . Now its not exported

2023-01-10 02:38 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Banner/content/Content.tsx
> +        <Button text={actionBtnOne} classname="primaryBtn" />
changed it into styleClass 😊

2023-01-10 02:39 UTC, urmirahman commented on apps/akij-food-beverage/src/styles/globals.css
> +    @apply rounded-full border border-green-500 py-4 px-6 text-center text-green-700  transition duration-300 hover:shadow-md hover:shadow-green-300;
removed the space 😊

2023-01-10 02:41 UTC, urmirahman commented on packages/ui/components/elements/Buttons/Button.tsx
> +};
new line added

2023-01-10 10:04 UTC, TanvirAlam submitted a review, later dismissed
LGTM! wait for other PR

2023-01-10 11:42 UTC, TanvirAlam approved these changes

2023-01-10 11:42 UTC, merged