feat: add a new feature in main section
AkijVenture/akij-turborepo pull request #89
Opened 2023-01-09 15:36 UTC by MuntasirAnik

# Description

A component is created  to add a new Feature as per ticket #82. 

Fixes # (issue)

   1. New Feature Added as Advance Section.
  
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code

<img width="1299" alt="2023-01-09 at 9 12 07 PM" src="https://user-images.githubusercontent.com/39253491/211344238-a6a783ed-a687-461f-b7aa-69f516ab4f69.png">

2023-01-10 12:04 UTC, TanvirAlam requested changes
looks good! do the chagnes and repush for approval

2023-01-11 10:20 UTC, MuntasirAnik commented on apps/akij-food-beverage/src/components/ui/features/AdvanceSection/Advance.tsx
> +interface Product {
Added in types

2023-01-11 11:29 UTC, urmirahman commented
@TanvirAlam  what happened here???

2023-01-11 11:36 UTC, TanvirAlam commented
@urmirahman build failed, see why

2023-01-11 18:38 UTC, TanvirAlam approved these changes
LGTM

2023-01-12 02:24 UTC, merged