feat: 📦 : Guide Component Added for Issue #85
AkijVenture/akij-turborepo pull request #90
Opened 2023-01-10 04:21 UTC by urmirahman

# Description
Guide Component added  for #78

Fixes #85 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Hero Section components are re-used with very few change

### No test has been done

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

# Output in Localhost:3010
Guide Section is similar to our Product section. Here is the output.

![guidesection](https://user-images.githubusercontent.com/44704518/211461078-86b59fb2-94f7-4d16-8d61-9decc455e17c.png)

Closes #85

2023-01-10 12:16 UTC, TanvirAlam requested changes
LGTM :+1: I like, think re-usability

2023-01-10 12:16 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/Guide/Products/Products.tsx
> +const Products = ({ products, error, loading }: any) => {
why dont you re-use the one we already have? you are creating the same component as this one: `src/components/features/Hero/Products.tsx`?

2023-01-10 12:24 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/Guide/Products/Products.tsx
> +const Products = ({ products, error, loading }: any) => {
need to add some style classes amd removed extra props divs.. this component is not entirely same as the hero/product Should have changed the component name??

2023-01-11 04:09 UTC, urmirahman commented
@TanvirAlam  I think all the conflicts have been removed . Please check.

2023-01-11 10:07 UTC, TanvirAlam approved these changes
LGTM :+1:

2023-01-11 10:10 UTC, merged