feat: added industry section on the bottom
AkijVenture/akij-turborepo pull request #92
Opened 2023-01-10 08:46 UTC by morshlab

# Description

Added industry section with named `akij-turborepo #83`

Fixes #83  (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
![image](https://user-images.githubusercontent.com/54287452/211503295-855d27e3-6001-4e28-8d49-329151ef3fc9.png)

2023-01-10 12:24 UTC, TanvirAlam requested changes

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +const Industry = () => {
please add empty space before

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +      }, [])
please add empty space

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +export default Industry;
please add new empty space

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/styles/globals.css
> +  }
please add empty new line

2023-01-10 12:24 UTC, TanvirAlam commented on packages/ui/components/elements/Icon/checkmark.tsx
> +  export default  Checkmark;
please add empty new line

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio explicabo soluta sapiente fugiat magni ipsa, neque delectus architecto </p>
why dnt you pass this as string? we have rule, NO static string in templates

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio explicabo soluta sapiente fugiat magni ipsa, neque delectus architecto </p>
why dont you pass this as string? we have rule, NO static string in templates

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio explicabo soluta sapiente fugiat magni ipsa, neque delectus architecto </p>
why dnt you pass this as string? we have rule, NO static string in templates

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +    useEffect(() => {
why do you have this hook? if you are not using it at all?

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                     <span>Resonable Price</span>
again static string

2023-01-10 12:24 UTC, TanvirAlam commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                      <CheckmarkIcon />
you are using this twice, why not make it into a components, you calling this twice or 3 times?

```
<div className="flex items-center space-x-2">
   <CheckmarkIcon />
   <span>Country Side</span>
 </div>
 ```

2023-01-10 12:24 UTC, TanvirAlam commented
LGTM, fix your merge and do the changes and push for approval

2023-01-10 12:26 UTC, TanvirAlam commented
@morshlab Make the Image bigger, look at the padding, fix them you are our CFO, yo? was up men

2023-01-12 02:35 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +const Industry = () => {
Empty space added

2023-01-12 02:35 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +      }, [])
Empty space added

2023-01-12 03:16 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio explicabo soluta sapiente fugiat magni ipsa, neque delectus architecto </p>
Creating new component for that

2023-01-12 03:16 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio explicabo soluta sapiente fugiat magni ipsa, neque delectus architecto </p>
creating new component for that

2023-01-12 03:34 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +    useEffect(() => {
useState is been used.

2023-01-12 03:34 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                     <span>Resonable Price</span>
making new component

2023-01-12 03:34 UTC, urmirahman commented on apps/akij-food-beverage/src/components/ui/features/IndustrySection.tsx
> +                      <CheckmarkIcon />
making new component

2023-01-12 03:56 UTC, urmirahman commented
@TanvirAlam  All conflicts has been gone. please check.

2023-01-12 08:20 UTC, TanvirAlam approved these changes
LGTM :+1: well done @urmirahman , yes try changing the them color to see the effect.

2023-01-12 08:25 UTC, merged